### PR TITLE
Add `CodeSnapPreviewOff` and auto close of servers on events

### PR DESCRIPTION
**Pull request by daUnknownCoder**
#16  
`CodeSnapPreviewOff`
Close of server on `VimLeavePre`, `BufDelete`, `InsertEnter`

### CODE REVIEW

**Comment by mistricky** [comment]
Hey @daUnknownCoder, thx for your PR. I'm wondering if this feature is necessary? cause frequently restart the server is an extra overhead compared to just keep the server running

**Comment by daUnknownCoder** [comment]
> Hey @daUnknownCoder, thx for your PR. I'm wondering if this feature is necessary? cause frequently restart the server is an extra overhead compared to just keep the server running

i use many neovim buffers like i open a file i would create a snapshot, the server stays connected even if i changed files or i changed the text so i changed that

**Comment by mistricky** [comment]
I have planned to refactor this plugin use lower graphic API, the architecture may have break change, this PR is may not be merge for now

**Comment by mistricky** [comment]
After refactor, there is no preview page anymore, this PR may out of stale, so closed. Thx for your contribute ❤️

**Comment by daUnknownCoder** [comment]
woah, rust to lua cool...

**Pull request closed without merging**
