### PR TITLE
[Chore] Update dependencies

### PR DESCRIPTION
**Pull request by Uzaaft**
Compilation of the current release fails for me: 
image

This PR fixes that by just bumping the deps. I took the liberty and updated most of the deps and fix breaking changes. The only outlier is the nvim-oxi crate.

One of the breaking changes requires a  LineEnding character to be passed into one of the functions. I default this to `\n` and whatever the windows equivalent is.

### CODE REVIEW

**Comment by Uzaaft** [comment]
Seems like the issue can be tracked to a new update of rust. Interesting...

**Review by mistricky — APPROVED** [review]
Wonderful, thx for your job

**Comment by mistricky** [comment]
Hi @Uzaaft, Will there be future commits on this PR? If not I'll merge it into main branch

**Comment by Uzaaft** [comment]
@mistricky  No. I won't be touching nvim-oxi. That shit is confusing me xD

**Comment by mistricky** [comment]
Yeah... FFI is really tricky thing to handle like what nvim-oxi did, if there a better solution to call Rust module in Lua, I would give it a try

**Pull request merged**
